FROM oven/bun:1.2-slim AS base

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

ENV NODE_ENV=development
RUN bun install --global nuekit

RUN chown -R 1000:1000 $BUN_INSTALL_BIN
RUN chown -R 1000:1000 $BUN_INSTALL_BIN/nue
RUN chmod -R a+rwx $BUN_INSTALL_BIN
RUN chmod -R a+rwx $BUN_INSTALL_BIN/nue

COPY . /app
WORKDIR ${FOLDER}

USER 1000:1000
RUN $BUN_INSTALL_BIN/nue -v
RUN nue -v

EXPOSE 3000/tcp
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["$HOME/.bun/bin/nue"]
